### ISSUE TITLE
Should the builder cache types?

### ISSUE THREAD

**Issue by MaikKlein** [google/rspirv#14]
For example:
```
    let void = b.type_void();
    let void1 = b.type_void();
```

results in

```
%2 = OpTypeVoid
%3 = OpTypeVoid
```

I expected just: 

```
%2 = OpTypeVoid
```
Should the builder cache types? Or should duplicate instructions be removed in a later stage?

**Comment by antiagainst** [comment]
The SPIR-V spec requires that "[Non-structure types (scalars, vectors, arrays, etc.) with the same operand parameterization cannot be type aliases.](https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.html#_universal_validation_rules)" So it is actually invalid to have two <result-id>s for the `void` type.

However, it is arguable whether this kind of "semantic" validation checks should happen in `mr::Builder`. `mr::Builder` is designed to be [low-level with little sanity check](https://docs.rs/rspirv/0.4.0/rspirv/mr/struct.Builder.html#errors). It is intended to be used by some higher level builder actually. (Sorry about this maybe unnecessary layers and abstractions.) Besides, [SPIR-V spec 2.16](https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.html#_a_id_validation_a_validation_rules) contains a bunch of validation rules. If we enable this one, what about the others?

I am planning a higher level builder (#5) and started [writing code for it](https://github.com/google/rspirv/tree/master/rspirv/sr), but cannot find time for it right now. We'll definitely need a type cache there. ;-P

**Comment by MaikKlein** [comment]
Okay sorry I haven't completely read the spec yet, I should probably do that now.
