### ISSUE TITLE
Update spirv_headers to version 1.3.1

### ISSUE THREAD

**Issue by dariost** [google/rspirv#28]
I've tried updating spirv_headers to version 1.3.1 with no luck (I was getting a `LiteralContextDependentNumber: this kind is not expected to be handled here`)
Now that Vulkan 1.1 supports SPIR-V 1.3 it would be nice if spirv_headers was upgraded to 1.3.1

**Comment by antiagainst** [comment]
Thanks @dariost for the interest! I'll take a look.

**Comment by antiagainst** [comment]
This is done in the master branch now. crates.io is also updated. Thanks!
