### ISSUE TITLE
Builder decorate methods don't have a way to specify extra decorator operands

### ISSUE THREAD

**Issue by tedsta** [google/rspirv#6]
https://github.com/google/rspirv/blob/a5a5d58385c7495df16407cb566cc51efbbd7213/rspirv/mr/build_annotation.rs#L21-L24

See https://www.khronos.org/registry/spir-v/specs/1.1/SPIRV.html#OpDecorate and https://www.khronos.org/registry/spir-v/specs/1.1/SPIRV.html#Decoration

Many decorations require additional operands. Strange that they don't include the extra operands in the SPIR-V grammar json. In particular, I'm trying to decorate a variable with the GlobalInvocationId BuiltIn.

**Comment by antiagainst** [comment]
Ouch! I should definitely add tests for the builder. The decoder and parser are extensively covered by tests, but the builder I delayed it a little bit, thinking that they are basically automatically generated and should be fine. But apparently not.

Yep, the grammar doesn't directly encode additional parameters to decorations in the `OpDecorate` instruction (or its siblings). They are encoded in the `Decoration` operand kind.

Thanks a lot for reporting! Will fix soon. :)

**Comment by antiagainst** [comment]
What is interesting is that if you check https://github.com/google/rspirv/commit/8411ea6bfb4ba03821bbaaba387715e1d5010ce9, the code removed were manually written and they did have the additional parameters. :)

**Comment by tedsta** [comment]
Ahhh haha. I do like your code generation though. Pretty slick.

**Comment by antiagainst** [comment]
Will push a new release soon

**Comment by tedsta** [comment]
Sweet, thank you!

**Comment by antiagainst** [comment]
Done. :)
